In \[1\]:

    import numpy as np

In \[4\]:

    rev_q1 = np.array([20,30,50])
    rev_q1.ndim

Out\[4\]:

    1

In \[6\]:

    rev_q2 = np.array([[20,30,50],[60,40,70]])
    rev_q2.ndim

Out\[6\]:

    2

In \[7\]:

    rev_q2

Out\[7\]:

    array([[20, 30, 50],
           [60, 40, 70]])

In \[9\]:

    rev_q2[1,2]

Out\[9\]:

    np.int64(70)

In \[10\]:

    rev_q2[1,2] = 60

In \[11\]:

    rev_q2

Out\[11\]:

    array([[20, 30, 50],
           [60, 40, 60]])

In \[12\]:

    rev_q2.dtype

Out\[12\]:

    dtype('int64')

In \[25\]:

    rev_q2 = np.array([[20,50,30],[50,40,70]],dtype = np.float64)

In \[26\]:

    rev_q2.dtype

Out\[26\]:

    dtype('float64')

In \[27\]:

    #ByteSize
    rev_q2.itemsize

Out\[27\]:

    8

In \[28\]:

    #Size means count
    rev_q2.size

Out\[28\]:

    6

In \[29\]:

    rev_q2.nbytes

Out\[29\]:

    48

In \[30\]:

    rev_q2.shape # Rows and columns

Out\[30\]:

    (2, 3)

In \[31\]:

    rev_q2

Out\[31\]:

    array([[20., 50., 30.],
           [50., 40., 70.]])

In \[32\]:

    np.sort(rev_q2) #Sorted

Out\[32\]:

    array([[20., 30., 50.],
           [40., 50., 70.]])

In \[33\]:

    np.sort(rev_q2,axis=None) #Flaten

Out\[33\]:

    array([20., 30., 40., 50., 50., 70.])

In \[34\]:

    np.zeros((2,3))

Out\[34\]:

    array([[0., 0., 0.],
           [0., 0., 0.]])

In \[35\]:

    np.ones((2,3))

Out\[35\]:

    array([[1., 1., 1.],
           [1., 1., 1.]])

In \[36\]:

    np.arange(20,30)

Out\[36\]:

    array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In \[37\]:

    np.arange(20,30,2)

Out\[37\]:

    array([20, 22, 24, 26, 28])

In \[38\]:

    np.linspace(10,20)

Out\[38\]:

    array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
           11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
           12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
           13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
           14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
           15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
           16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
           17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
           18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
           19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In \[39\]:

    np.linspace(10,20,5)

Out\[39\]:

    array([10. , 12.5, 15. , 17.5, 20. ])

In \[43\]:

    np.linspace(10,20,20) # start,stop,stepSize

Out\[43\]:

    array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
           12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
           15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
           17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In \[44\]:

    rev_q2.ravel() # It won't Modify

Out\[44\]:

    array([20., 50., 30., 50., 40., 70.])

In \[47\]:

    rev_q2.flatten()

Out\[47\]:

    array([20., 50., 30., 50., 40., 70.])

In \[48\]:

    rev_q2.reshape(3,2) # Reshaped Columns rows make sure compatable

Out\[48\]:

    array([[20., 50.],
           [30., 50.],
           [40., 70.]])

In \[49\]:

    rev_q2.min()

Out\[49\]:

    np.float64(20.0)

In \[50\]:

    rev_q2.max() # Numpy is Implemented in C lang it is too fast

Out\[50\]:

    np.float64(70.0)

In \[51\]:

    rev_q2.sum() # Entire Sum

Out\[51\]:

    np.float64(260.0)

In \[52\]:

    rev_q2.sum(axis = 1) # at Row level sum

Out\[52\]:

    array([100., 160.])

In \[53\]:

    rev_q2.sum(axis = 0) # Vertically / Col level sum

Out\[53\]:

    array([ 70.,  90., 100.])

In \[55\]:

    rev_q2

Out\[55\]:

    array([[20., 50., 30.],
           [50., 40., 70.]])

In \[56\]:

    for row in rev_q2:
        print("row --> ", row)

    row -->  [20. 50. 30.]
    row -->  [50. 40. 70.]

In \[57\]:

    b = np.array([1,4,16])

In \[58\]:

    np.sqrt(b)

Out\[58\]:

    array([1., 2., 4.])

In \[60\]:

    np.square(b)

Out\[60\]:

    array([  1,  16, 256])

In \[61\]:

    np.std(b)

Out\[61\]:

    np.float64(6.48074069840786)

use Numpy Doc for Syntax

You Don't have to remember API syntax.In Real Life People always refer
Numpy Doc,chatgpt or google to know Syntax

sum(),min(),max(),std() are used for doing quick statistical analysis

ndim,itemsize,size,shape are the functions used for figuringout an
array's dimensions,elements byte size,total number of elements,and the
size of each dimension,respectively.