<a href="https://colab.research.google.com/github/ChandraMouli2727/Rough/blob/main/DL/Matrix_Basics_10_Cost_loss_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expense = np.array([[80,90,100],[10,16,20],[8,10,10]])
expense

array([[ 80,  90, 100],
       [ 10,  16,  20],
       [  8,  10,  10]])

In [ ]:
revenue

array([[180, 200, 220],
       [ 24,  36,  40],
       [ 12,  18,  20]])

In [ ]:
profit = revenue - expense
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [ ]:
price = np.array([[1000,400,1200]])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])
price

array([[1000,  400, 1200]])

In [ ]:
sales = price * units
sales

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [ ]:
np.dot(price,units)

array([[34400, 50000, 64400]])

In [ ]:
rev = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
price=np.array([[96]])
total = price * rev
total

array([[19200, 21120, 24000],
       [ 6528,  7584, 10080],
       [10560, 13440, 17280],
       [ 7680,  8160,  8640]])

# Matrix Math is fun to learn Matrix multiplication
https://www.mathsisfun.com/algebra/matrix-introduction.html

# Cost & Loss functions

# Tensorflow loss value examples


*   sparse_categorical_crossentropy
*   binary_crossentropy
*   categorical_crossentropy
*   mean_absolute_error
*   mean_squared_error

Why not MSE for logistic regression:
https://towardsdatascience.com/why-no...

In [ ]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [ ]:
def mae(y_true,y_predicted):
  total_error = 0
  for yt,yp in zip(y_true,y_predicted):
    total_error += abs(yt-yp)
  print("Total error:",total_error)
  mae = total_error/len(y_true)
  print("MAE:",mae)
  return mae

In [ ]:
mae(y_true,y_predicted)

Total error: 2.5
MAE: 0.5


np.float64(0.5)

In [ ]:
y_predicted-y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [ ]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [ ]:
np.mean(np.abs(y_predicted-y_true))

np.float64(0.5)

In [ ]:
np.sum(np.abs(y_predicted-y_true))

np.float64(2.5)

In [ ]:
np.square(y_predicted-y_true)

array([0.49, 0.09, 1.  , 0.  , 0.25])

In [ ]:
np.mean(np.square(y_predicted-y_true))

np.float64(0.366)

In [ ]:
np.mean((y_true-y_predicted)**2)

np.float64(0.366)

In [ ]:
np.log([0])

/tmp/ipykernel_5501/262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [ ]:
np.log([0.0000000000])

/tmp/ipykernel_5501/3431205333.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0.0000000000])


array([-inf])

In [ ]:
epsilon = 1e-15

In [ ]:
y_predicted

array([1, 1, 0, 0, 1])

In [ ]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[np.int64(1), np.int64(1), 1e-15, 1e-15, np.int64(1)]

In [ ]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new # which is close to 0/1 but not 0/1

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [ ]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [ ]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [ ]:
np.log(y_predicted)

/tmp/ipykernel_5501/815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

# Log loss or binary cross entropy

In [ ]:
y_true = np.array(y_true)                # convert list to array
y_predicted_new = np.array(y_predicted_new)

loss = -np.mean(
    y_true * np.log(y_predicted_new) +
    (1 - y_true) * np.log(1 - y_predicted_new)
)

print("Binary cross-entropy loss:", loss)


Binary cross-entropy loss: 17.2696280766844


In [ ]:
def log_loss(y_true,y_predicted):
  epsilon = 1e-15
  y_predicted_new = [max(i,epsilon) for i in y_predicted]
  y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
  y_predicted_new = np.array(y_predicted_new)
  return -np.mean(
      y_true * np.log(y_predicted_new) +
      (1 - y_true) * np.log(1 - y_predicted_new)
  )

In [ ]:
log_loss(y_true,y_predicted)

np.float64(17.2696280766844)