In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
#Numpy array occupies less memory compare to python list

In [6]:
l = [1,2,3]
l


[1, 2, 3]

In [21]:
python_l = list(range(100))
python_l[0:10]
# size/length of this list is 100
#Python supports Non-Homogeneous Elements
# It occupies metadata also so memory is high memory is fragmented slowness also

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
import sys
sys.getsizeof(python_l[0]) * len(python_l) # In Bytes


2800

In [22]:
numpy_arr = np.arange(100)
numpy_arr[0:10]
#It occupies contiguous memory , memory is less,fast retrival

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#sys.getsizeof(numpy_arr[0]) * len(numpy_arr)
numpy_arr.nbytes


800

In [28]:
l1 = [1,2,3]
l2 = [4,5,6]
zip(l1,l1)
tuple(zip(l1,l2))

for x,y in zip(l1,l2):
    print(x,y)

1 4
2 5
3 6


In [41]:
import time
size = 1000000
l1 = list(range(size))
l2 = list(range(size))

start_time = time.time()
l3 = [x+y for x,y in zip(l1,l2)]
end_time = time.time()
print("Python List Tooks",end_time - start_time)
# late retrival compare to numpy array

Python List Tooks 0.16443371772766113


In [33]:
n1 = np.arange(size)
n2 = np.arange(size)
n1[:3],n2[:4]

(array([0, 1, 2]), array([0, 1, 2, 3]))

In [42]:
start_time = time.time()
n3 = n1 + n2
end_time = time.time()
print("Numpy Array tooks",end_time-start_time)
#fast retrival

Numpy Array tooks 0.00613856315612793


In [43]:
#Convenient Use With Built In Functions

In [49]:
l1 = list(range(5))
l2 = list(range(5))
l1[:3],l2[:3]
l1 + l2
# It's Doing concatenation

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [51]:
l3 = [x+y for x,y in zip(l1,l2)]
l3


[0, 2, 4, 6, 8]

In [52]:
n1 = np.arange(5)
n2 = np.arange(5)
n1[:3],n2[:3]
n1 + n2
# 

array([0, 2, 4, 6, 8])

In [55]:
n1 * n2,n1-n2

(array([ 0,  1,  4,  9, 16]), array([0, 0, 0, 0, 0]))

Numpy (Numeric Python) is a popular library used for data analysis,machine learning and scientific Computing.
Any Person Doing Data analysis or Machine learning in python uses numpy almost on a Daily basis
Numpy arrays offers several benefits over plain python list such as

* less memory Consumption
* Fast Operations
* Convenient Apis for Variety Mathematical Functions