In [1]:
import numpy as np

In [2]:
#Sales Data for Quarter 1 (Matrix 1)
# Rows Represent Different Products,Columns represent Diferrent Regions USA India China , Iphone Ipod ,Macbook

q1 = np.array([
      [200,220,250], # Product A
      [150,180,210], # Product B
      [300,330,360]  # Product C
])
q2 = np.array([
      [209,231,259], # Product A
      [155,192,222], # Product B
      [310,340,375]  # Product C
])


In [3]:
q = q1 + q2
q

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [4]:
q2-q1 # Diff units between quarter

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [5]:
# In terms of Percentage
(q2-q1)*100/q1


array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [6]:
prices = np.array([
   [10,12,11], # Prices for Product A in Different regions
   [8,9,10],   # Prices for Product B
   [15,16,17]
])

q1_rev = q1 * prices
q1_rev

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 6120]])

In [7]:
 # If you give discount 
q1_discounts = q1_rev * 0.2 # Multiply with scalar value (single value)
q1_discounts


array([[ 400.,  528.,  550.],
       [ 240.,  324.,  420.],
       [ 900., 1056., 1224.]])

In [8]:
net_rev = q1_rev - q1_discounts
net_rev


array([[1600., 2112., 2200.],
       [ 960., 1296., 1680.],
       [3600., 4224., 4896.]])

In [9]:
np.sum(q1_discounts) # To check total discounts

np.float64(5642.0)

In [10]:
np.sum(net_rev)

np.float64(22568.0)

In [11]:
q2_rev = q2 * prices
q2_rev


array([[2090, 2772, 2849],
       [1240, 1728, 2220],
       [4650, 5440, 6375]])

In [12]:
# Need To explore dot Product & Croos Product in Matrices

features = np.array([
     [2000,3], # House 1 sq,bed room
     [1800,2]  # House 2
])
weights = np.array([150,50000])
# 2000 * 150 + 3 * 50000
np.dot(features,weights)



array([450000, 370000])

In [13]:
c = np.array([1,2,3])
d = np.array([4,5,6])
np.cross(c,d)
#(c2d3-c3d2,c1d3-c3d1,c1d2-c2d1)

array([-3,  6, -3])

* Using Numpy,One can perform Matrix Operations in a convenient way
 * For two Matrices (m1 and m2), one can do addition,subtraction,division, and multiplication by using +,-,/ and * Operators

 *np.dot(m1,m2) and np.cross(m1,m2) can be used to perform a dot and cross products between two metrices (m1 and m2)

