In [1]:
import numpy as np

In [2]:
a = np.array([6,7,8,9])

In [3]:
a[0:2] # start : Inclusive , end = Not Include

array([6, 7])

In [4]:
a[2:]

array([8, 9])

In [22]:
a[-1]

np.int64(9)

In [23]:
a[-2]

np.int64(8)

In [24]:
a[-2:]

array([8, 9])

In [5]:
b = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
b[1,2]

np.int64(6)

In [27]:
b[2,0]

np.int64(7)

In [28]:
b[-1]

array([7, 8, 9])

In [7]:
b[-1,0:2]

array([7, 8])

In [8]:
b[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [9]:
# Customer Id , Name
c = np.array([
       [101,'Mira'],
       [102,'Abdul'],
       [103,'Andrea']
])
#Customer Id,Purchase amount ,Release Date
d = np.array([
    [101,250.50 ,'2026-03-28'],
    [102,150.00,'2026-03-29'],
    [103,300.75,'2026-03-30']
])


In [10]:
#Horizontal Stack
np.hstack((c,d)) #Give like a Tuple


array([['101', 'Mira', '101', '250.5', '2026-03-28'],
       ['102', 'Abdul', '102', '150.0', '2026-03-29'],
       ['103', 'Andrea', '103', '300.75', '2026-03-30']], dtype='<U32')

In [11]:
c

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea']], dtype='<U21')

In [12]:
e = np.array([
             [104,'sam'],
             [105,'Ram'],
             [106,'Tom']
])
e


array([['104', 'sam'],
       ['105', 'Ram'],
       ['106', 'Tom']], dtype='<U21')

In [13]:
#Vertical Stack
np.vstack((c,e))


array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'sam'],
       ['105', 'Ram'],
       ['106', 'Tom']], dtype='<U21')

In [14]:
transactions = np.array([
       [101, 'Mira',250.5, '2026-03-28'],
       [102, 'Abdul',150.0, '2026-03-29'],
       [103, 'Andrea',300.75, '2026-03-30'],
       [104,'ram',400,'2026-03-31'],
       [105,'sam',500,'2026-04-01']
       ])
transactions

array([['101', 'Mira', '250.5', '2026-03-28'],
       ['102', 'Abdul', '150.0', '2026-03-29'],
       ['103', 'Andrea', '300.75', '2026-03-30'],
       ['104', 'ram', '400', '2026-03-31'],
       ['105', 'sam', '500', '2026-04-01']], dtype='<U32')

In [15]:
#horizontal split the columns
np.hsplit(transactions,[3])


[array([['101', 'Mira', '250.5'],
        ['102', 'Abdul', '150.0'],
        ['103', 'Andrea', '300.75'],
        ['104', 'ram', '400'],
        ['105', 'sam', '500']], dtype='<U32'),
 array([['2026-03-28'],
        ['2026-03-29'],
        ['2026-03-30'],
        ['2026-03-31'],
        ['2026-04-01']], dtype='<U32')]

In [16]:
a,b = np.hsplit(transactions,[2])
a

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'ram'],
       ['105', 'sam']], dtype='<U32')

In [17]:
b

array([['250.5', '2026-03-28'],
       ['150.0', '2026-03-29'],
       ['300.75', '2026-03-30'],
       ['400', '2026-03-31'],
       ['500', '2026-04-01']], dtype='<U32')

In [18]:
#Vertical split
np.vsplit(transactions,[4])

[array([['101', 'Mira', '250.5', '2026-03-28'],
        ['102', 'Abdul', '150.0', '2026-03-29'],
        ['103', 'Andrea', '300.75', '2026-03-30'],
        ['104', 'ram', '400', '2026-03-31']], dtype='<U32'),
 array([['105', 'sam', '500', '2026-04-01']], dtype='<U32')]

In [19]:

x,y = np.vsplit(transactions,[2])
x


array([['101', 'Mira', '250.5', '2026-03-28'],
       ['102', 'Abdul', '150.0', '2026-03-29']], dtype='<U32')

In [20]:
y

array([['103', 'Andrea', '300.75', '2026-03-30'],
       ['104', 'ram', '400', '2026-03-31'],
       ['105', 'sam', '500', '2026-04-01']], dtype='<U32')

In [21]:
# monthly sales revenue
monthly_sales = np.array([30,35,33,28,42])
result = monthly_sales < 32
result

array([ True, False, False,  True, False])

In [22]:
monthly_sales[result] # conveninet passing to get those values

array([30, 28])

In [23]:
monthly_sales.max()

np.int64(42)

In [24]:
#for getting index of max value
index = np.argmax(monthly_sales)
index

np.int64(4)

In [25]:
monthly_sales[index]

np.int64(42)

In [26]:
transactions

array([['101', 'Mira', '250.5', '2026-03-28'],
       ['102', 'Abdul', '150.0', '2026-03-29'],
       ['103', 'Andrea', '300.75', '2026-03-30'],
       ['104', 'ram', '400', '2026-03-31'],
       ['105', 'sam', '500', '2026-04-01']], dtype='<U32')

In [27]:
#for first get a col to find max
aa = transactions[:,2]
aa #<U32 is unicode it is a string

array(['250.5', '150.0', '300.75', '400', '500'], dtype='<U32')

In [28]:

aa = transactions[:,2].astype(float)
aa 

array([250.5 , 150.  , 300.75, 400.  , 500.  ])

In [29]:
trans_index = np.argmax(aa)
trans_index


np.int64(4)

In [30]:
transactions[trans_index]

array(['105', 'sam', '500', '2026-04-01'], dtype='<U32')

In [31]:
transactions[:,0]

array(['101', '102', '103', '104', '105'], dtype='<U32')

In [78]:
transactions[transactions[:,0] == '102']

array([['102', 'Abdul', '150.0', '2026-03-29']], dtype='<U32')

* Numpy Supports index and slicing operation similiar to python native list
* np.hstack and np.vstack are used to stack two numpy arrays horizontally and vertically
* np.hsplit and np.vsplit are used to split a numpy array either horizontally or vertically